### ISSUE TITLE
! ! ERROR --> A module is not installed...

### ISSUE THREAD

**Issue by Haruke-Sensei** [berkaymizrak/Proxy-Scraper-Checker#4]
![image](https://user-images.githubusercontent.com/87328375/127970858-f0fe8ad2-18db-4972-97b7-db3bda27d28b.png)

**Comment by berkaymizrak** [comment]
I guess there is problem with python-docx. 

> _"The exceptions module is a python2 module. This module has been removed in python3."_

If you use python 3.x could you paste:
pip3 uninstall docx
pip install python-docx
